gesCommandes/Controllers/CommandeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gesCommandes.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using gesCommandes.Models;
using gesCommandes.Enums;
using System.Text.Json;
using Newtonsoft.Json;
using System.Security.Claims;

namespace gesCommandes.Controllers
{
    [Authorize]
    [Authorize(Roles = nameof(Role.RS))]
    public class CommandeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommandeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Commande
        public IActionResult Index()
        {
            var commandes = _context.Commandes
                .Include(c => c.client)
                    .ThenInclude(client => client.user) // Include user related to client
                .Include(c => c.livreur)
                .Include(c => c.paiement)
                .ToList();
            if (commandes != null)
            {
                Console.WriteLine($"❌Found {commandes.Count} commandes❌");
            }
            ViewBag.commandes = commandes;
            return View("Index");
        }

        // GET: Commande/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes
                .Include(c => c.client)
                .Include(c => c.livreur)
                .Include(c => c.paiement)
                .Include(c => c.detailCommandes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // GET: Commande/Create
        
    }
}

gesCommandes/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gesCommandes.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using gesCommandes.Models;
using gesCommandes.Enums;
using System.Text.Json;
using Newtonsoft.Json;
using System.Security.Claims;
using System;
using System.IO;
using System.Threading.Tasks;
using System.Web;

namespace gesCommandes.Controllers
{
    [Authorize]
    [Authorize(Roles = nameof(Role.CLIENT) + "," + nameof(Role.RS))]
    public class ProduitController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProduitController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Produit
        public async Task<IActionResult> Index()
        {
            int userId = HttpContext.Session.GetInt32("userId").Value;
            var client = _context.Clients
                .Include(c => c.user)
                .FirstOrDefault(c => c.userId == userId);
            var produits = await _context.Produits.ToListAsync();
            if (HttpContext.Session.GetObject<List<DetailCommande>>("Panier") == null)
            {
                HttpContext.Session.SetObject("Panier", new List<DetailCommande>());
            }

            var panier = HttpContext.Session.GetObject<List<DetailCommande>>("Panier");
            ViewData["PanierCount"] = panier.Count;
            ViewBag.Client = client;
            return View(produits);
        }

        // GET: Produit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetObject<List<DetailCommande>>("Panier") == null)
            {
                HttpContext.Session.SetObject("Panier", new List<DetailCommande>());
            }

            var panier = HttpContext.Session.GetObject<List<DetailCommande>>("Panier");
            ViewData["PanierCount"] = panier.Count;

            return View(produit);
        }

        // GET: Produit/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> save(Produit produit)
        {
            if (ModelState.IsValid)
            {
                if (produit.ImgFile != null)
                {
                    var uploadsFolder = Path.Combine("wwwroot", "imgs", "produits");

                    Directory.CreateDirectory(uploadsFolder);

                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + produit.ImgFile.FileName;
                    var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await produit.ImgFile.CopyToAsync(fileStream);
                    }

                    produit.ImgPath = $"/imgs/produits/{uniqueFileName}";
                }

                _context.Produits.Add(produit);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(produit);
        }


        // POST: Produit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Libelle,Prix,QteStock,Id,CreatedAt,UpdatedAt")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produit/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Libelle,Prix,QteStock,Id,ImgFile,ImgPath,CreatedAt,UpdatedAt")] Produit produit)
        {
            if (id != produit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }


        private bool ProduitExists(int id)
        {
            return _context.Produits.Any(e => e.Id == id);
        }

        // GET: Produit/Delete/5
        // [HttpPost, ActionName("Delete")]
        // [ValidateAntiForgeryToken]
        [HttpGet("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrWhiteSpace(produit.ImgPath))
            {
                var imagePath = Path.Combine("wwwroot", produit.ImgPath.TrimStart('/'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _context.Produits.Remove(produit);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


    }
}

gesCommandes/Views/Shared/NotFound.cshtml
<!-- Views/Shared/NotFound.cshtml -->
@{
    ViewData["Title"] = "Page Not Found";
}

<h1>404 - Page Not Found</h1>
<p>Sorry, the page you are looking for does not exist.</p>

gesCommandes/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@using gesCommandes.Enums;

@{
    var paniercount = ViewData["PanierCount"];
    var client = ViewData["Client"] as Client ?? new Client { user = new User { Nom = "Unknown" } };
    var currentUser = (ClaimsPrincipal)User; // Cast the User to ClaimsPrincipal
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - gesCommandes</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/favicon_io/site.webmanifest">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="/css/output.css">
    @* <link rel="stylesheet" href="css/output.css?v=@DateTime.Now.Ticks"> *@
    <link rel="stylesheet" href="/css/site.css">
    @RenderSection("stylesheets", required: false)
</head>

<body class=" bg-opacity-80 bg-custom-pattern bg-custom-size bg-custom-position w-full m-0 h-screen p-0" style="background-color: rgba(255,250,235,1);
opacity: 1;
background-image: radial-gradient(#243132 2px, rgba(255,250,235,1) 2px);
background-size: 40px 40px;">
    <nav class="border-gray-200 bg-greenMe flex items-center justify-between w-full m-0">
        <div class=" flex items-center justify-center py-4 bg-green-600 w-auto">
            <a href="@Url.Action("Index", "Home")" class="flex items-center ">
                <span class="self-center text-xl font-semibold text-white p-1">GES_COMMANDES</span>
            </a>
        </div>
        <div class="flex items-center justify-between gap-8 px-5 text-white ">
            @if (currentUser.FindFirstValue(ClaimTypes.Role) == Role.CLIENT.ToString())
            {
                <a asp-action="CreateCommande" asp-controller="Client" asp-route-clientId="@client.Id"
                    class="relative mr-3 flex items-center text-white hover:underline">
                    <i class="fa-solid fa-cart-shopping text-2xl"></i>
                    <span
                        class="absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2 bg-red-500 text-xs text-white rounded-full px-1">
                        @ViewData["PanierCount"]
                    </span>
                </a>

            }
            <div class="bg-yellow-50 rounded-full w-10 h-10">
                @if (currentUser.FindFirstValue(ClaimTypes.Role) == Role.RS.ToString())
                {
                    <img src="@(currentUser.FindFirstValue(ClaimTypes.UserData) != null ? currentUser.FindFirstValue(ClaimTypes.UserData) : "/imgs/users/default2.png")"
                        alt="No image Here" class="object-fit w-full h-full rounded-full" />
                }
                else if (client.user != null && client.user.Id != null)
                {
                    <img src="@(client.user.ImgPath != null ? client.user.ImgPath : "/imgs/users/default2.png")"
                        alt="No image Here" class="object-fit w-full h-full rounded-full" />
                }
                else
                {
                    <img src="/imgs/users/default2.png" alt="No image Here" class="object-fit w-full h-full rounded-full" />
                }
            </div>

        </div>
    </nav>

    <div class="flex w-full m-0" style="height: calc(100vh - 65px);">
        <aside class="bg-greenMe p-6  sticky top-0 left-0 bottom-0  flex justify-between flex-col">
            <ul class="space-y-2 font-medium">
                @if (currentUser.FindFirstValue(ClaimTypes.Role) == Role.CLIENT.ToString())
                {
                    <li>
                        <a href="@Url.Action("Commandes", "Client", new { userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier) })"
                            class="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-user-group w-5 h-5"></i>
                            <span class="ms-3">Commandes</span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Produit")"
                            class="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-box w-5 h-5"></i>
                            <span class="ms-3">Produits</span>
                        </a>
                    </li>
                    <li>
                        <a asp-action="Paiements" asp-controller="Client" asp-route-clientId="@client.Id"
                            class="lex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-money-check w-5 h-5"></i>
                            Paiements
                        </a>
                    </li>
                }
                @if (currentUser.FindFirstValue(ClaimTypes.Role) == Role.RS.ToString())
                {
                    <li>
                        <a href="@Url.Action("Index", "Client" , new { userId = currentUser.FindFirstValue(ClaimTypes.NameIdentifier) })"
                            class="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-users w-5 h-5"></i>
                            <span class="ms-3">Clients</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Commande")"
                            class="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-user-group w-5 h-5"></i>
                            <span class="ms-3">Commandes</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Produit")"
                            class="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                            <i class="fa-solid fa-box w-5 h-5"></i>
                            <span class="ms-3">Produits</span>
                        </a>
                    </li>
                }
            </ul>
            <a href="@Url.Action("Logout", "User")"
                class="text-white py-3 px-5 rounded-lg bg-green-600 hover:underline text-center">Logout</a>
        </aside>

        <main class="flex p-4 w-full " style="background-color: #e5e7eb;
opacity: 1;
background-image:  radial-gradient(#243132 1.05px, transparent 1.05px), radial-gradient(#243132 1.05px, #e5e7eb 1.05px);
background-size: 42px 42px;
background-position: 0 0,21px 21px;">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted text-center py-4 m-0 bg-greenMe text-white">
        <div>&copy; 2024 - gesCommandes - <a href="@Url.Action("Privacy", "Home")" class="hover:underline">Privacy</a>
        </div>
    </footer> *@

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
    @* <script>
        const checkbox = document.getElementById('creerCompte');
        const userFields = document.getElementById('userFields');

        function toggleUserFields() {
            const userInputs = userFields.querySelectorAll('input, select');

            if (checkbox.checked) {
                userFields.classList.remove('hidden');
                userInputs.forEach(input => input.setAttribute('required', 'required'));
            } else {
                userFields.classList.add('hidden');
                userInputs.forEach(input => input.removeAttribute('required'));
            }
        }

        // Initialize on load
        toggleUserFields();

        // Attach change event listener
        checkbox.addEventListener('change', toggleUserFields);
    </script> *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>

gesCommandes/Views/Shared/_connexionLayout.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - gesCommandes</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>gc</text></svg>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="/css/output.css">
    @RenderSection("stylesheets", required: false)
</head>
<body class=" bg-opacity-80 bg-custom-pattern bg-custom-size bg-custom-position">

        <main class="flex p-4 justify-center items-center bg-white h-screen">
            @RenderBody()
        </main>

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>